server:
  port: 8081

spring:
  application:
    name: eureka-client2
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka,http://peer3:8763/eureka
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

